/**
 * DEPRECATED - This file is a stub to prevent import errors
 * All financial data is now managed by DataContext and fetched from the backend
 * Use DataContext methods: addFinancialEntry, updateFinancialEntry, deleteFinancialEntry
 */

import { financialCategories, financialStatuses } from "./financialConstants";

// Re-export constants for backwards compatibility
export { financialCategories, financialStatuses };

// Stub financial ledger - empty array
export const financialLedger = [];

// Deprecated stub functions - these should not be used
// Use DataContext methods instead
export const addFinancialEntry = () => {
  console.error("[financialData] DEPRECATED: Use DataContext.addFinancialEntry instead");
  return { entry: null, result: { allowed: false, blockers: ["Use DataContext methods"] } };
};

export const updateFinancialEntry = () => {
  console.error("[financialData] DEPRECATED: Use DataContext.updateFinancialEntry instead");
  return { entry: null, result: { allowed: false, blockers: ["Use DataContext methods"] } };
};

export const deleteFinancialEntry = () => {
  console.error("[financialData] DEPRECATED: Use DataContext.deleteFinancialEntry instead");
  return { success: false, result: { allowed: false, blockers: ["Use DataContext methods"] } };
};

export const setFinancialLedger = () => {
  console.warn("[financialData] DEPRECATED: setFinancialLedger is no longer needed");
};

export const getNextFinancialId = () => {
  console.error("[financialData] DEPRECATED: IDs are now generated by the backend");
  return 0;
};

export default financialLedger;
