import {
  AlibabaLogo,
  AnthropicLogo,
  AzureLogo,
  BedrockLogo,
  CohereLogo,
  DeepSeekLogo,
  GemmaLogo,
  GeminiLogo,
  GenericAILogo,
  GoogleLogo,
  GroqLogo,
  HuggingFaceLogo,
  IBMLogo,
  MetaLogo,
  MicrosoftLogo,
  MistralLogo,
  MoonshotLogo,
  NousResearchLogo,
  OllamaLogo,
  OpenAILogo,
  OpenRouterLogo,
  QwenLogo,
  SnowflakeLogo,
  TIILogo,
  UpstageLogo,
  YiLogo,
  ZeroOneLogo,
} from "./ProviderLogos";

export const PROVIDER_LOGOS = {
  anthropic: AnthropicLogo,
  openai: OpenAILogo,
  openrouter: OpenRouterLogo,
  groq: GroqLogo,
  google: GoogleLogo,
  gemini: GeminiLogo,
  gemma: GemmaLogo,
  azure: AzureLogo,
  bedrock: BedrockLogo,
  meta: MetaLogo,
  microsoft: MicrosoftLogo,
  alibaba: AlibabaLogo,
  qwen: QwenLogo,
  yi: YiLogo,
  ollama: OllamaLogo,
  deepseek: DeepSeekLogo,
  cohere: CohereLogo,
  huggingface: HuggingFaceLogo,
  mistral: MistralLogo,
  moonshot: MoonshotLogo,
  kimi: MoonshotLogo,
  ibm: IBMLogo,
  snowflake: SnowflakeLogo,
  "01ai": ZeroOneLogo,
  lmsys: GenericAILogo,
  tii: TIILogo,
  upstage: UpstageLogo,
  wizardlm: GenericAILogo,
  nousresearch: NousResearchLogo,
  nomic: GenericAILogo,
  mixedbread: GenericAILogo,
  custom: GenericAILogo,
  other: GenericAILogo,
} as const;

export const PROVIDER_LOGO_AVATARS = {
  anthropic: AnthropicLogo.Avatar,
  openai: OpenAILogo.Avatar,
  openrouter: OpenRouterLogo.Avatar,
  groq: GroqLogo.Avatar,
  google: GoogleLogo.Avatar,
  gemini: GeminiLogo.Avatar,
  gemma: GemmaLogo.Avatar,
  azure: AzureLogo.Avatar,
  bedrock: BedrockLogo.Avatar,
  meta: MetaLogo.Avatar,
  microsoft: MicrosoftLogo.Avatar,
  alibaba: AlibabaLogo.Avatar,
  qwen: QwenLogo.Avatar,
  yi: YiLogo.Avatar,
  ollama: OllamaLogo.Avatar,
  deepseek: DeepSeekLogo.Avatar,
  cohere: CohereLogo.Avatar,
  huggingface: HuggingFaceLogo.Avatar,
  mistral: MistralLogo.Avatar,
  moonshot: MoonshotLogo.Avatar,
  kimi: MoonshotLogo.Avatar,
  ibm: IBMLogo.Avatar,
  snowflake: SnowflakeLogo.Avatar,
  "01ai": ZeroOneLogo.Avatar,
  lmsys: GenericAILogo.Avatar,
  tii: TIILogo.Avatar,
  upstage: UpstageLogo.Avatar,
  wizardlm: GenericAILogo.Avatar,
  nousresearch: NousResearchLogo.Avatar,
  nomic: GenericAILogo.Avatar,
  mixedbread: GenericAILogo.Avatar,
  custom: GenericAILogo.Avatar,
  other: GenericAILogo.Avatar,
} as const;

export type ProviderKey = keyof typeof PROVIDER_LOGOS;
